name:  CI
env:
  # Common versions
  GO_VERSION: "1.21"
on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2
      - name: Setup Go environment
        uses: actions/setup-go@v5.5.0
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Build Binaries
        run: |
          make -C node build ARCH=amd64
      - name: Save binaries
        uses: actions/upload-artifact@v4.6.2
        with:
          name: calico-node-amd64
          path: /home/runner/work/calico/calico/node/dist/bin/calico-node-amd64
      - name: Build Image
        run: |
          make -C node image ARCH=amd64
      - name: Login to DockerHub
        uses: docker/login-action@v3.4.0
        with:
          username: songdi676
          password: qq8856676
      - name: push
        run: |
          docker push songdi676/node:latest-amd64